PRELOAD: on
LOG: off
BUCKET: 'fixed'
BUCKET_CONF:
  count: 150
ITERATIONS: 1
DEBUG: on

FEATURE_KERNEL:
    COUNT: 500
    MIN_TIME: 25
    MAX_TIME: 50
    CACHE_FILE: 'feature.dat'
    POLICY: 'min-feasible'

