PRELOAD: on
LOG: on
BUCKET: 'fixed'
BUCKET_CONF:
  count: 15
ITERATIONS: 2
TIME_LIMIT: 30
DEBUG: '30n20b8-run.csv'
SOLUTION_FILE: '30n20b8-sol.sol'
MIP_GAP: 4.0


FEATURE_KERNEL:
    COUNT: 150
    MIN_TIME: 10
    MAX_TIME: 25
    POLICY: 'min-infeasible'
    LOG_FILE: '30n20b8-init.csv'
    
