PRELOAD: on
LOG: on
BUCKET: 'fixed'
BUCKET_CONF:
  count: 15
ITERATIONS: 2
DEBUG: 'in-run.csv'
SOLUTION_FILE: 'in-sol.sol'
MIP_GAP: 4.0


FEATURE_KERNEL:
    COUNT: 50
    MIN_TIME: 120
    MAX_TIME: 170
    POLICY: 'min-feasible'
    LOG_FILE: 'in-init.csv'
    CACHE_FILE: 'in-cache.dat'
    
