PRELOAD: on
LOG: on
BUCKET: 'fixed'
BUCKET_CONF:
  count: 150
ITERATIONS: 1
DEBUG: 'bab2-run.csv'
SOLUTION_FILE: 'bab2-sol.sol'


FEATURE_KERNEL:
    COUNT: 0
    MIN_TIME: 45
    MAX_TIME: 60
    POLICY: 'max-feasible'
    LOG_FILE: 'bab2-log.csv'
    CACHE_FILE: 'bab2-cache.dat'
    
