PRELOAD: on
LOG: on
BUCKET: 'fixed'
BUCKET_CONF:
  count: 15
ITERATIONS: 2
DEBUG: 'bab6-run.csv'
SOLUTION_FILE: 'bab6-sol.sol'
MIP_GAP: 4.0


FEATURE_KERNEL:
    COUNT: 50
    MIN_TIME: 10
    MAX_TIME: 40
    POLICY: 'min-feasible'
    LOG_FILE: 'bab6-init.csv'
    CACHE_FILE: 'bab6-cache.dat'
    
