PRELOAD: on
LOG: on
BUCKET: 'fixed'
BUCKET_CONF:
  count: 15
ITERATIONS: 2
DEBUG: 'bab2-run.csv'
SOLUTION_FILE: 'bab2-sol.sol'


FEATURE_KERNEL:
    COUNT: 50
    MIN_TIME: 45
    MAX_TIME: 90
    POLICY: 'min-infeasible'
    LOG_FILE: 'bab2-log.csv'
    
