PRELOAD: on
LOG: on
BUCKET: 'fixed'
BUCKET_CONF:
  count: 1500
ITERATIONS: 1
DEBUG: on

FEATURE_KERNEL:
    COUNT: 10
    MIN_TIME: 25
    MAX_TIME: 50
    CACHE_FILE: 'feature.dat'
    POLICY: 'min-infeasible'

