PRELOAD: on
LOG: off
BUCKET: 'fixed'
BUCKET_CONF:
  count: 15
ITERATIONS: 2
DEBUG: 'atlanta_ip-run.csv'
SOLUTION_FILE: 'atlanta_ip-sol.sol'


FEATURE_KERNEL:
    COUNT: 50
    MIN_TIME: 45
    MAX_TIME: 60
    POLICY: 'min-infeasible'
    LOG_FILE: 'atlanta_ip-log.csv'
    
