PRELOAD: on
LOG: on
BUCKET: 'fixed'
BUCKET_CONF:
  count: 125
ITERATIONS: 1
TIME_LIMIT: 300
DEBUG: 'in-run.csv'
SOLUTION_FILE: 'in-sol.sol'
MIP_GAP: 4.0
PRESOLVE: true


#FEATURE_KERNEL:
#    COUNT: 150
#    MIN_TIME: 10
#    MAX_TIME: 20
#    POLICY: 'min-infeasible'
#    LOG_FILE: 'in-init.csv'
    
