PRELOAD: on
LOG: on
BUCKET: 'fixed'
BUCKET_CONF:
  count: 15
ITERATIONS: 3
DEBUG: 'neos-run.csv'

FEATURE_KERNEL:
    COUNT: 0
    MIN_TIME: 25
    MAX_TIME: 50
    CACHE_FILE: 'neos-cache.dat'
    POLICY: 'min-infeasible'
    LOG_FILE: 'neos-log.csv'
