PRELOAD: on
LOG: on
BUCKET: 'fixed'
BUCKET_CONF:
  count: 20
ITERATIONS: 10
TIME_LIMIT: 15
DEBUG: 'atlanta-ip-run.csv'
SOLUTION_FILE: 'atlanta-ip-sol.sol'
MIP_GAP: 4.0
PRESOLVE: true
WORST-SOL: false
KERNEL-GROWTH: false
REMOVE-UNSET: true
   
