PRELOAD: on
LOG: on
BUCKET: 'fixed'
BUCKET_CONF:
  count: 20
ITERATIONS: 2
TIME_LIMIT: 30
DEBUG: 'probportfolio-run.csv'
SOLUTION_FILE: 'probportfolio-sol.sol'
MIP_GAP: 4.0
PRESOLVE: true
WORST-SOL: false
KERNEL-GROWTH: true
REMOVE-UNSET: true
PROBLEM-KICKSTART: false
DISTILL: false
