PRELOAD: on
LOG: on
BUCKET: 'fixed'
BUCKET_CONF:
  count: 2
ITERATIONS: 4
TIME_LIMIT: 50
DEBUG: 'bab6-no-worst-run.csv'
SOLUTION_FILE: 'bab6-no-worst-sol.sol'
MIP_GAP: 4.0
PRESOLVE: true
WORST-SOL: false

   
