PRELOAD: on
LOG: off
BUCKET: 'fixed'
BUCKET_CONF:
  count: 35
ITERATIONS: 2
TIME_LIMIT: 15
DEBUG: 'bg5112142-run.csv'
SOLUTION_FILE: 'bg5112142-sol.sol'
MIP_GAP: 4.0
PRESOLVE: true
WORST-SOL: false
KERNEL-GROWTH: true
REMOVE-UNSET: true
PROBLEM-KICKSTART: false
DISTILL: false
