PRELOAD: on
LOG: off
BUCKET: 'fixed'
BUCKET_CONF:
  count: 15
ITERATIONS: 6
TIME_LIMIT: 30
DEBUG: 'irish-run.csv'
SOLUTION_FILE: 'irish-sol.sol'
MIP_GAP: 4.0
PRESOLVE: true


#FEATURE_KERNEL:
#    COUNT: 150
#    MIN_TIME: 10
#    MAX_TIME: 20
#    POLICY: 'min-infeasible'
#    LOG_FILE: 'in-init.csv'
    
