PRELOAD: on
LOG: on
BUCKET: 'fixed'
BUCKET_CONF:
  count: 35
ITERATIONS: 2
TIME_LIMIT: 15
DEBUG: 'sct32-run.csv'
SOLUTION_FILE: 'sct32-sol.sol'
MIP_GAP: 4.0
PRESOLVE: true
WORST-SOL: false
KERNEL-GROWTH: true
REMOVE-UNSET: true
PROBLEM-KICKSTART: false
DISTILL: false
